### ISSUE TITLE
minor changes

### ISSUE THREAD

**Issue by vfabregat** [markjulmar/atapi.net#1]
Hi! nice library!

Just a remark, in the codeplex site, the url to the moved github is pointing to https://github.com/markjulmar/atapi/ and this site is the C/C++ wrapper.

Do you accept pull request? I my current project we add some minor features:
* Abstractions for the main entities, such as TapiLine, TapiCall, TapiAddress. In order to allow mocking those entities in unit tests.
* Added a GUID in the calls to identify it each call as unique.

I can send you a pull request if you want. 

Regards.

**Comment by markjulmar** [comment]
Absolutely will take PRs! I’ll fix the codeplex forward link – thanks!

Those features sound perfect – take care,

mark

From: Victor
Sent: Monday, September 18, 2017 12:23 AM
To: markjulmar/atapi.net
Cc: Subscribed
Subject: [markjulmar/atapi.net] minor changes (#1)

Hi! nice library!
Just a remark, in the codeplex site, the url to the moved github is pointing to https://github.com/markjulmar/atapi/ and this site is the C/C++ wrapper.
Do you accept pull request? I my current project we add some minor features:
• Abstractions for the main entities, such as TapiLine, TapiCall, TapiAddress. In order to allow mocking those entities in unit tests.
• Added a GUID in the calls to identify it each call as unique.
I can send you a pull request if you want.
Regards.

**Comment by vfabregat** [comment]
Nice! I'll prepare it and sent you it!

**Comment by vfabregat** [comment]
Hi again @markjulmar,

I sent you the pull request, if you see any problem, let me know to fix it.

This change include intefaces for tapicall and tapi address.

Do you will publish it as a nuget package?

**Comment by markjulmar** [comment]
Perfect – thanks Victor, let me review the changes and make a few adjustments!

mark
