### ISSUE TITLE
Trouble getting a SIP Device 

### ISSUE THREAD

**Issue by pwrp4j1** [markjulmar/atapi.net#26]
Hi, I am working using the atapi 64 bit dll and using it to query the CUCM 11.5 system for lines. However, I only see the lines associated with Cisco devices, not SIP devices. Any ideas why this maybe? 

My configuration settings in the CUCM admin part is exactly the same for all 3 devices and my SIP Device can "talk" and "call" the other devices OK. I have associated a line, device and unique user to the SIP device, similar to the other ones.

```
_tapiManager = new TapiManager("Hills.CiscoCallManager");
                
                _tapiManager.LineAdded += this._tapiManager_LineAdded;
                _tapiManager.LineRemoved += this._tapiManager_LineRemoved;

                Logger.Info("Initialising Tapi Manager..");
                var pass = _tapiManager.Initialize();

// now when I query the Lines Property, I do not see the SIP Device in there.
```

thanks,
Randeep

**Comment by rum80** [comment]
Hello Randeep,
I am quite sure that issue is not related to ATAPI at all, but due to a CUCM misconfiguration.

To be sure: just open a TAPI client, such as phone.exe, see [here](https://support.act-crm-addon.de/Knowledgebase/Article/View/66/0/how-to-use-phoneexe--testing-your-local-tapi), and look whether those SIP lines are present or not.

If, as I think, SIP lines are not present, I suggest to check permission of the CUCM Application User you're using. In particular, ensure user has privileges: 
- Standard CTI Allow Control of Phones supporting Connected Xfer and conf 
- Standard CTI Allow Control of Phones supporting Rollover Mode

BTW, the right place to investigate Cisco CTI issue is [this forum](https://community.cisco.com/t5/call-control/bd-p/j-disc-dev-collab-call-control).

Regards, Marco.

**Comment by pwrp4j1** [comment]
Hello Marco, 

Indeed you are right and thank you for posting the answer so quickly. After further reading and exploring, I discovered that 3rd Party SIP Devices do not have this flag to turn on for calling monitoring: 
"Allow Control of Device from CTI".

So, even after setting the permissions as you stated in your email I couldn't get access to the phones (even using phone.exe). 

Thank you for the resources provided, I will close this issue now as it needs to be answered by Cisco really. 

Randeep
