### ISSUE TITLE
How to use atapi.net in web API 

### ISSUE THREAD

**Issue by patelnitesha** [markjulmar/atapi.net#6]
Hello,

We have got a requirement where we would like to monitor the incoming call and from fin the related user from that phone number and display the user details on the screen. Also want to create  a phone link where user can call the that number directly from the link.  
WE have got similar functionality in our older version but it uses the Vbscript.  We have got TAPi installed. i just need a way to way to monitor this in our new system. (front end is Ember and backend is web API in C#)

Kind Regards

**Comment by portison** [comment]
What you are describing sounds like standard screen-popping and click-to-call functionality. atapi.net can help you to develop that functionality in .net for a phone system that support TAPI. 

Atapi.net is a relatively thin, .net wrapper around TAPI 2.x  rather than a CTI development toolkit, so you'll need a level of understanding of TAPI 2.x programming to make full use of it.  

I can recommend Microsoft's TAPI browser for trying out TAPI.

If your TAPI software is going to be server-side and monitoring/controlling multiple lines at the same time, then you'll need to install a 3rd Party TSP from your phone system rather than a 1st Party one.

Assuming your requirement is to lookup callers based on their CLI (and that's quite an assumption), then there's a couple of different ways you could get the CLI. You could register a CallStateChanged handler and look for Offering / Connected events OR you could register a CallInfoChanged event and look for the CallerId changing. We use both events in our screen-popping applications. In either/both cases, you'd then use the CallerId to do a search of your "customer" database or CRM. manually-entered Telephone number data in databases and CRMs is notoriously dirty with spaces, brackets and other text often included - so your search may need to take that into consideration or you may need to run a data cleansing exercise on your telephone number data.

For your click-to-call requirement, the atapi method to make a call is TapiLine.MakeCall(string address)
